import type { Order } from "../_types";

export const orders: Order[] = [
  {
    id: "ORD-2024-001",
    customer: "John Doe",
    email: "john@example.com",
    products: 3,
    total: "$1,245.00",
    date: "15 Jan 2024",
    status: "Completed",
    payment: "Paid",
  },
  {
    id: "ORD-2024-002",
    customer: "Jane Smith",
    email: "jane@example.com",
    products: 1,
    total: "$590.00",
    date: "14 Jan 2024",
    status: "Processing",
    payment: "Paid",
  },
  {
    id: "ORD-2024-003",
    customer: "Bob Wilson",
    email: "bob@example.com",
    products: 2,
    total: "$834.00",
    date: "14 Jan 2024",
    status: "Pending",
    payment: "Pending",
  },
  {
    id: "ORD-2024-004",
    customer: "Alice Brown",
    email: "alice@example.com",
    products: 5,
    total: "$2,150.00",
    date: "13 Jan 2024",
    status: "Shipped",
    payment: "Paid",
  },
  {
    id: "ORD-2024-005",
    customer: "Charlie Davis",
    email: "charlie@example.com",
    products: 1,
    total: "$234.00",
    date: "13 Jan 2024",
    status: "Completed",
    payment: "Paid",
  },
  {
    id: "ORD-2024-006",
    customer: "Diana Evans",
    email: "diana@example.com",
    products: 4,
    total: "$1,890.00",
    date: "12 Jan 2024",
    status: "Cancelled",
    payment: "Refunded",
  },
  {
    id: "ORD-2024-007",
    customer: "Edward Foster",
    email: "edward@example.com",
    products: 2,
    total: "$678.00",
    date: "12 Jan 2024",
    status: "Completed",
    payment: "Paid",
  },
  {
    id: "ORD-2024-008",
    customer: "Fiona Grant",
    email: "fiona@example.com",
    products: 3,
    total: "$1,456.00",
    date: "11 Jan 2024",
    status: "Processing",
    payment: "Paid",
  },
];
